### ISSUE TITLE
紅米note5/sd636

### ISSUE THREAD

**Issue by delphinuz** [yc9559/cpufreq-interactive-opt#13]
第一次嘗試，使用Scene載入，設定為省電，但大核被鎖在最高頻1804MHz，小核被锁在最低頻636。

嘗試手動執行powercfg.sh，但也是同樣的結果。

**Comment by yc9559** [comment]
先处理perfboostsconfig和温控，然后再试

**Comment by delphinuz** [comment]
重新開機後好了，但遇到一個問題二次，就是手機無反應，螢幕全黑，只能長按power強制重新開機。

SOT與待機時間明顯延長約1～2小時(省電模式）。

再測試幾天看看，希望不會再發生上面的情況。

**Comment by yc9559** [comment]
推荐尝试[wipe-v2 190503](https://github.com/yc9559/wipe-v2/releases/tag/0.1.190503-dev)，使用前同样关闭perfboostsconfig和温控，否则会冲突

**Comment by delphinuz** [comment]
不好意思，我是用v2版，只是不小心在v1這裡留言。(是否重新在v2開個Issue?)
目前是使用Scene，線上載入v2版的636版powercfg.sh，使用SmartPack-KernelManager来看相關參數。

perfboostsconfig：Scene好像没得關？在鑭系統工具箱裡有個Performance boost配置，已手動關閉。
溫控：核心/VDD/SOC三個都是關的。

另外剛手動在Scene由均衡切换到省電時，又出現大核被鎖在最高頻1804MHz，重開機後再切換幾次就沒再出現大核鎖在1804MHz的情況，不知是否powercfg.sh還有bug?

**Comment by yc9559** [comment]
考虑到小米有私有温控，光关闭核心/VDD/SOC这三个高通的模块是不够的，大核锁最高基本都是这些原因，在原生系统上没有这些附加模块是可以直接使用的。镧工具箱似乎有删除私有温控的功能，或者到酷安搜索删除小米温控的办法。

**Comment by delphinuz** [comment]
我是使用Havoc，找到鑭工具箱刪除的選項。再測試幾天，有問題會在v2的issue反饋。
