### ISSUE TITLE
关于performance(费电/游戏)参数的疑问

### ISSUE THREAD

**Issue by m809311563** [yc9559/cpufreq-interactive-opt#4]
对于游戏来说不同游戏不同优化程度和对cpu gpu要求不同，所以感觉很难能做到通过参数来完美的实现丝滑顺畅
         针对目前参数想单独开个问题来讨论performance配置的改进(因为目前感觉还是有小问题存在的)
首先有几个小问题(只是想请教交流下😂毕竟不太懂)
1 gpu调度能否对游戏产生更好体验
2 IO调速器有没有明显影响(理论上来说)
3 新增加的  sched_freq_inc_notify  会不会导致在游戏过程中出现大负载时导致满频在随后频率降低时导致不能满足当前负载而导致卡顿(飞车我会感觉到有时候会莫名的卡顿一秒钟有时候，吃鸡也是这样，容易有一小段时间很卡，然后又恢复流畅。当然，这两者的垃圾优化也有很大影响，不过还是希望考虑下看有没有可能改进。最近我也没怎么注意频率的问题，等考完试过后五一回家多抽些时间测试下)
         这两天没怎么测试太多，忙着考试，抽空会跑两把飞车，打局王者，吃盘🐔总的来说感觉跟之前v2很像，而且最新版也是说明了基于v2来改进的，这版本就是感觉吃鸡的情况下大小核频率经常乱跳😂我总感觉是这样容易导致造成卡顿
         再就是过后再重新开个问题来反馈下酷安上的回答和这版(82x我看了下好像并未做更改，还是最后测试版的数据)的测试，感觉看到了两个比较多的问题。
         之所以想到来git上来反馈是感觉酷安回复人太多了😂反馈也是各种不同的问题，单开一个也比较清净，毕竟来这的人少😋

**Comment by yc9559** [comment]
有想法很好。
gpu调度如果有好的建议，可以做到脚本里面。
IO有影响，我偏向CFQ。
`sched_freq_inc_notify`正是为了解决卡顿一秒钟。
其实跟V2差别太多了，换了损失函数的话手感会完全不同。
有问题早点提，别堆到发公开测试版

**Comment by m809311563** [comment]
Gpu调度貌似说ondemand不错，然而我现在系统并改不到那个调速器，所以没法测试
Cfq之前找了找没在文件中找到也就搁置了
以后有问题肯定及时反馈

**Comment by m809311563** [comment]
![](https://i.imgur.com/a5QOvKm.png)
![](https://i.imgur.com/kJJjL5m.png)
gpu是默认的msm adreno tz
IO改了cfq 512
这版测试看起来performance的配置感觉像是稳定了
测了下飞车全高的情况下大核心更容易集中稳定在14xx－15xx，这是跑的时候抽空看一眼perfmon，看起来反映在频率分布上也差不多
小核心更加均匀分布了😳看起来是这样，之前都是1286比较多，附近的频率比例则很少，这一般貌似占比增加了
而且目前没感觉到飞车像之前那样突然卡一下的情况了，吃鸡均衡40帧也是这样，不过还是会有些小卡顿，回头我也注意下卡顿时频率情况

**Comment by yc9559** [comment]
谢谢测试。最低频还在处理中，正在尝试不固定为85是否能有更好的结果。

**Comment by m809311563** [comment]
嗯嗯，意思是想让5xx左右频率分布均匀些么？

**Comment by yc9559** [comment]
主要是为了更好的亮屏续航上限

**Comment by m809311563** [comment]
![](https://i.imgur.com/n1zQHNm.png)
这是昨天(0429)推的后面一版
图中频率是performance配置下两小时十分钟的小核频率分布，貌似小核心在10xx的分布有所提升
这版跑飞车的时候大核基本一直在1516，偶尔会有波动，但是感觉没有0428那样流畅，0428那一版大核心比较容易跑到1593，但是没有这版频率稳定感觉
总体感觉上是性能没有上版高，但是比上版稳定，不知道是不是这样😂

**Comment by m809311563** [comment]
没那么流畅倒不是会有很明显的卡顿，就是感觉有点不跟手，可能是今天感觉问题，但是感觉比上版频率稳定倒是绝对的

**Comment by yc9559** [comment]
收到，打算微调一下，降低above的限制，应该会有改善

**Comment by m809311563** [comment]
好的✌️👍

**Comment by yc9559** [comment]
已更新

**Comment by m809311563** [comment]
Ok👍我去换配置
